// https://adventofcode.com/2025/day/7

static EXAMPLE_INPUT: &str = r#"
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"#;

use super::*;

#[test]
fn part1_example() {
    assert_eq!(
        TachyonManifold::new(EXAMPLE_INPUT)
            .simulate()
            .num_beam_splits,
        21
    );
}

#[test]
fn part2_example() {
    assert_eq!(
        TachyonManifold::new(EXAMPLE_INPUT).simulate().num_timelines,
        40
    );
}
